### ISSUE TITLE
Debug server side

### ISSUE THREAD

**Issue by MartinGian** [mauricedb/server-side-rendering-with-create-react-app#2]
Hi!

Cool project. I have a question, is there a way to debug the server side express middlewares? Using vscode.

Thank you!

**Comment by mauricedb** [comment]
@MartinGian That is really easy in VSCode. Make sure the client app is built first using `yarn build` Then start VS-Code and open `./server/index.js` and press F5. It will start it with the debugger attached. Put a breakpoint somewhere in the `router.get("/", ...)` in `./server/react-app.js`. Open a browser at `http://localhost:3001` and you should see the code stopping at the breakpoint.
